//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Rezerv
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET.Business;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Календарь.
    /// </summary>
    // *** Start programmer edit section *** (Календарь CustomAttributes)

    // *** End programmer edit section *** (Календарь CustomAttributes)
    [BusinessServer("IIS.Rezerv.План, Rezerv.Objects", ICSSoft.STORMNET.Business.DataServiceObjectEvents.OnAllEvents)]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КалендарьE", new string[] {
            "Конец as \'Конец\'",
            "Трудозатраты as \'Трудозатраты\'",
            "Начало as \'Начало\'",
            "Участник as \'Участник\'",
            "Участник.ФИО as \'ФИО\'"}, Hidden=new string[] {
            "Участник.ФИО"})]
    [MasterViewDefineAttribute("КалендарьE", "Участник", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    public class Календарь : ICSSoft.STORMNET.DataObject
    {
        
        private string fКонец;
        
        private int fТрудозатраты;
        
        private string fНачало;
        
        private IIS.Rezerv.Участник fУчастник;
        
        private IIS.Rezerv.План fПлан;
        
        // *** Start programmer edit section *** (Календарь CustomMembers)

        // *** End programmer edit section *** (Календарь CustomMembers)

        
        /// <summary>
        /// Конец.
        /// </summary>
        // *** Start programmer edit section *** (Календарь.Конец CustomAttributes)

        // *** End programmer edit section *** (Календарь.Конец CustomAttributes)
        [StrLen(255)]
        public virtual string Конец
        {
            get
            {
                // *** Start programmer edit section *** (Календарь.Конец Get start)

                // *** End programmer edit section *** (Календарь.Конец Get start)
                string result = this.fКонец;
                // *** Start programmer edit section *** (Календарь.Конец Get end)

                // *** End programmer edit section *** (Календарь.Конец Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Календарь.Конец Set start)

                // *** End programmer edit section *** (Календарь.Конец Set start)
                this.fКонец = value;
                // *** Start programmer edit section *** (Календарь.Конец Set end)

                // *** End programmer edit section *** (Календарь.Конец Set end)
            }
        }
        
        /// <summary>
        /// Начало.
        /// </summary>
        // *** Start programmer edit section *** (Календарь.Начало CustomAttributes)

        // *** End programmer edit section *** (Календарь.Начало CustomAttributes)
        [StrLen(255)]
        public virtual string Начало
        {
            get
            {
                // *** Start programmer edit section *** (Календарь.Начало Get start)

                // *** End programmer edit section *** (Календарь.Начало Get start)
                string result = this.fНачало;
                // *** Start programmer edit section *** (Календарь.Начало Get end)

                // *** End programmer edit section *** (Календарь.Начало Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Календарь.Начало Set start)

                // *** End programmer edit section *** (Календарь.Начало Set start)
                this.fНачало = value;
                // *** Start programmer edit section *** (Календарь.Начало Set end)

                // *** End programmer edit section *** (Календарь.Начало Set end)
            }
        }
        
        /// <summary>
        /// Трудозатраты.
        /// </summary>
        // *** Start programmer edit section *** (Календарь.Трудозатраты CustomAttributes)

        // *** End programmer edit section *** (Календарь.Трудозатраты CustomAttributes)
        public virtual int Трудозатраты
        {
            get
            {
                // *** Start programmer edit section *** (Календарь.Трудозатраты Get start)

                // *** End programmer edit section *** (Календарь.Трудозатраты Get start)
                int result = this.fТрудозатраты;
                // *** Start programmer edit section *** (Календарь.Трудозатраты Get end)

                // *** End programmer edit section *** (Календарь.Трудозатраты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Календарь.Трудозатраты Set start)

                // *** End programmer edit section *** (Календарь.Трудозатраты Set start)
                this.fТрудозатраты = value;
                // *** Start programmer edit section *** (Календарь.Трудозатраты Set end)

                // *** End programmer edit section *** (Календарь.Трудозатраты Set end)
            }
        }
        
        /// <summary>
        /// Календарь.
        /// </summary>
        // *** Start programmer edit section *** (Календарь.Участник CustomAttributes)

        // *** End programmer edit section *** (Календарь.Участник CustomAttributes)
        [PropertyStorage(new string[] {
                "Участник"})]
        [NotNull()]
        public virtual IIS.Rezerv.Участник Участник
        {
            get
            {
                // *** Start programmer edit section *** (Календарь.Участник Get start)

                // *** End programmer edit section *** (Календарь.Участник Get start)
                IIS.Rezerv.Участник result = this.fУчастник;
                // *** Start programmer edit section *** (Календарь.Участник Get end)

                // *** End programmer edit section *** (Календарь.Участник Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Календарь.Участник Set start)

                // *** End programmer edit section *** (Календарь.Участник Set start)
                this.fУчастник = value;
                // *** Start programmer edit section *** (Календарь.Участник Set end)

                // *** End programmer edit section *** (Календарь.Участник Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Rezerv.План.
        /// </summary>
        // *** Start programmer edit section *** (Календарь.План CustomAttributes)

        // *** End programmer edit section *** (Календарь.План CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "План"})]
        public virtual IIS.Rezerv.План План
        {
            get
            {
                // *** Start programmer edit section *** (Календарь.План Get start)

                // *** End programmer edit section *** (Календарь.План Get start)
                IIS.Rezerv.План result = this.fПлан;
                // *** Start programmer edit section *** (Календарь.План Get end)

                // *** End programmer edit section *** (Календарь.План Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Календарь.План Set start)

                // *** End programmer edit section *** (Календарь.План Set start)
                this.fПлан = value;
                // *** Start programmer edit section *** (Календарь.План Set end)

                // *** End programmer edit section *** (Календарь.План Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КалендарьE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КалендарьE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КалендарьE", typeof(IIS.Rezerv.Календарь));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Календарь.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfКалендарь CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfКалендарь CustomAttributes)
    public class DetailArrayOfКалендарь : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Rezerv.DetailArrayOfКалендарь members)

        // *** End programmer edit section *** (IIS.Rezerv.DetailArrayOfКалендарь members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Календарь by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Календарь.
        /// </summary>
        public DetailArrayOfКалендарь(IIS.Rezerv.План fПлан) : 
                base(typeof(Календарь), ((ICSSoft.STORMNET.DataObject)(fПлан)))
        {
        }
        
        public IIS.Rezerv.Календарь this[int index]
        {
            get
            {
                return ((IIS.Rezerv.Календарь)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Rezerv.Календарь dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
