//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Rezerv
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// План.
    /// </summary>
    // *** Start programmer edit section *** (План CustomAttributes)

    // *** End programmer edit section *** (План CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПланE", new string[] {
            "Проект as \'Проект\'",
            "Проект.Наименование as \'Наименование\'",
            "Проект.Срок as \'Срок окончания\'",
            "Проект.Участник.ФИО as \'Руководитель проекта\'"}, Hidden=new string[] {
            "Проект.Наименование"})]
    [AssociatedDetailViewAttribute("ПланE", "Календарь", "КалендарьE", true, "", "Календарь", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ПланE", "Проект", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [View("ПланL", new string[] {
            "Проект.Наименование as \'Наименование\'",
            "Проект.Участник as \'Руководитель проекта\'",
            "Проект.Срок as \'Срок окончания проекта\'",
            "Проект.Стоимость as \'Бюджет проекта\'"})]
    public class План : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Rezerv.Проект fПроект;
        
        private IIS.Rezerv.DetailArrayOfКалендарь fКалендарь;
        
        // *** Start programmer edit section *** (План CustomMembers)

        // *** End programmer edit section *** (План CustomMembers)

        
        /// <summary>
        /// План.
        /// </summary>
        // *** Start programmer edit section *** (План.Проект CustomAttributes)

        // *** End programmer edit section *** (План.Проект CustomAttributes)
        [PropertyStorage(new string[] {
                "Проект"})]
        [NotNull()]
        public virtual IIS.Rezerv.Проект Проект
        {
            get
            {
                // *** Start programmer edit section *** (План.Проект Get start)

                // *** End programmer edit section *** (План.Проект Get start)
                IIS.Rezerv.Проект result = this.fПроект;
                // *** Start programmer edit section *** (План.Проект Get end)

                // *** End programmer edit section *** (План.Проект Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (План.Проект Set start)

                // *** End programmer edit section *** (План.Проект Set start)
                this.fПроект = value;
                // *** Start programmer edit section *** (План.Проект Set end)

                // *** End programmer edit section *** (План.Проект Set end)
            }
        }
        
        /// <summary>
        /// План.
        /// </summary>
        // *** Start programmer edit section *** (План.Календарь CustomAttributes)

        // *** End programmer edit section *** (План.Календарь CustomAttributes)
        public virtual IIS.Rezerv.DetailArrayOfКалендарь Календарь
        {
            get
            {
                // *** Start programmer edit section *** (План.Календарь Get start)

                // *** End programmer edit section *** (План.Календарь Get start)
                if ((this.fКалендарь == null))
                {
                    this.fКалендарь = new IIS.Rezerv.DetailArrayOfКалендарь(this);
                }
                IIS.Rezerv.DetailArrayOfКалендарь result = this.fКалендарь;
                // *** Start programmer edit section *** (План.Календарь Get end)

                // *** End programmer edit section *** (План.Календарь Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (План.Календарь Set start)

                // *** End programmer edit section *** (План.Календарь Set start)
                this.fКалендарь = value;
                // *** Start programmer edit section *** (План.Календарь Set end)

                // *** End programmer edit section *** (План.Календарь Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// Редактирование плана.
            /// </summary>
            public static ICSSoft.STORMNET.View ПланE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПланE", typeof(IIS.Rezerv.План));
                }
            }
            
            /// <summary>
            /// "ПланL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПланL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПланL", typeof(IIS.Rezerv.План));
                }
            }
        }
    }
}
