//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Rezerv
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Проект.
    /// </summary>
    // *** Start programmer edit section *** (Проект CustomAttributes)

    // *** End programmer edit section *** (Проект CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПроектE", new string[] {
            "Стоимость as \'Стоимость\'",
            "Наименование as \'Наименование\'",
            "Срок as \'Срок\'",
            "Участник as \'Участник\'",
            "Участник.ФИО as \'ФИО\'"}, Hidden=new string[] {
            "Участник.ФИО"})]
    [MasterViewDefineAttribute("ПроектE", "Участник", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [View("ПроектL", new string[] {
            "Стоимость as \'Стоимость\'",
            "Наименование as \'Наименование\'",
            "Срок as \'Срок\'",
            "Участник.ФИО as \'ФИО\'"})]
    public class Проект : ICSSoft.STORMNET.DataObject
    {
        
        private int fСтоимость;
        
        private string fНаименование;
        
        private string fСрок;
        
        private IIS.Rezerv.Участник fУчастник;
        
        // *** Start programmer edit section *** (Проект CustomMembers)

        // *** End programmer edit section *** (Проект CustomMembers)

        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Проект.Наименование CustomAttributes)

        // *** End programmer edit section *** (Проект.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Проект.Наименование Get start)

                // *** End programmer edit section *** (Проект.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Проект.Наименование Get end)

                // *** End programmer edit section *** (Проект.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Проект.Наименование Set start)

                // *** End programmer edit section *** (Проект.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Проект.Наименование Set end)

                // *** End programmer edit section *** (Проект.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Срок.
        /// </summary>
        // *** Start programmer edit section *** (Проект.Срок CustomAttributes)

        // *** End programmer edit section *** (Проект.Срок CustomAttributes)
        [StrLen(255)]
        public virtual string Срок
        {
            get
            {
                // *** Start programmer edit section *** (Проект.Срок Get start)

                // *** End programmer edit section *** (Проект.Срок Get start)
                string result = this.fСрок;
                // *** Start programmer edit section *** (Проект.Срок Get end)

                // *** End programmer edit section *** (Проект.Срок Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Проект.Срок Set start)

                // *** End programmer edit section *** (Проект.Срок Set start)
                this.fСрок = value;
                // *** Start programmer edit section *** (Проект.Срок Set end)

                // *** End programmer edit section *** (Проект.Срок Set end)
            }
        }
        
        /// <summary>
        /// Стоимость.
        /// </summary>
        // *** Start programmer edit section *** (Проект.Стоимость CustomAttributes)

        // *** End programmer edit section *** (Проект.Стоимость CustomAttributes)
        public virtual int Стоимость
        {
            get
            {
                // *** Start programmer edit section *** (Проект.Стоимость Get start)

                // *** End programmer edit section *** (Проект.Стоимость Get start)
                int result = this.fСтоимость;
                // *** Start programmer edit section *** (Проект.Стоимость Get end)

                // *** End programmer edit section *** (Проект.Стоимость Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Проект.Стоимость Set start)

                // *** End programmer edit section *** (Проект.Стоимость Set start)
                this.fСтоимость = value;
                // *** Start programmer edit section *** (Проект.Стоимость Set end)

                // *** End programmer edit section *** (Проект.Стоимость Set end)
            }
        }
        
        /// <summary>
        /// Проект.
        /// </summary>
        // *** Start programmer edit section *** (Проект.Участник CustomAttributes)

        // *** End programmer edit section *** (Проект.Участник CustomAttributes)
        [PropertyStorage(new string[] {
                "Участник"})]
        [NotNull()]
        public virtual IIS.Rezerv.Участник Участник
        {
            get
            {
                // *** Start programmer edit section *** (Проект.Участник Get start)

                // *** End programmer edit section *** (Проект.Участник Get start)
                IIS.Rezerv.Участник result = this.fУчастник;
                // *** Start programmer edit section *** (Проект.Участник Get end)

                // *** End programmer edit section *** (Проект.Участник Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Проект.Участник Set start)

                // *** End programmer edit section *** (Проект.Участник Set start)
                this.fУчастник = value;
                // *** Start programmer edit section *** (Проект.Участник Set end)

                // *** End programmer edit section *** (Проект.Участник Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПроектE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПроектE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПроектE", typeof(IIS.Rezerv.Проект));
                }
            }
            
            /// <summary>
            /// "ПроектL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПроектL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПроектL", typeof(IIS.Rezerv.Проект));
                }
            }
        }
    }
}
